### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by TomDSlankard** [twslankard/mfingpdfer#2]
Toms-MacBook-Pro:~ tslankard$ python3 mfingpdfer.py WS13939.csv WS13939.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/toilets/2017/2989101-cadet-3-flowise-right-height-elongated-toilet/spec-sheet-2989101.pdf?la=en -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/spec-sheet-2989101.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet0476028.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet0476028.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bathroom-sink-faucets/2017/serin-widespread-bathroom-faucet-2064831/specsheet-2064831.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet-2064831.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet2395202.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet2395202.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet2395202.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet2395202.pdf
Downloading https://www.americanstandard-us.com/bathroom/bath-drains/deep-soak-tub-drain-16434?variant=polished-chrome -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/deep-soak-tub-drain-16434
Downloading http://web.western-sales.com//specs/spec_%20tu064500wdxh.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/spec_%20tu064500wdxh.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet1660710.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet1660710.pdf
Downloading http://western-sales.com/specs/RU10xspec.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/RU10xspec.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet6034st.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet6034st.pdf
Downloading http://web.western-sales.com//specs/spec_%20tu064500wdxh.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/spec_%20tu064500wdxh.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet1660710.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet1660710.pdf
Downloading http://western-sales.com/specs/RU10xspec.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/RU10xspec.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheett064430.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheett064430.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet-r422.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet-r422.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/shower-accessories/30-inch-standard-shower-slide-bar-1660730/spec-sheet-1660730.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/spec-sheet-1660730.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet8888068.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet8888068.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/bulk/specsheet8888035.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet8888035.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/commercial-showers/2017/specsheet-1660766.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet-1660766.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/kitchen-sinks/2017/colony/specsheet-22sb6252283s075.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/specsheet-22sb6252283s075.pdf
Downloading https://www.americanstandard-us.com/-/media/sites/asus/files/product-specs/kitchen-faucets/colony-pro-kitchen-faucets/colonyprosckitchfaucet7074000.pdf -> ./downloaded_files/1f386dfd60caebf4d392dd076f46d43d/colonyprosckitchfaucet7074000.pdf
Done downloading.
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
Traceback (most recent call last):
  File "mfingpdfer.py", line 56, in <module>
    create_pdfs(rows, args.output_pdf)
  File "mfingpdfer.py", line 42, in create_pdfs
    merger.append(row[2]) 
  File "/Users/tslankard/Library/Python/3.8/lib/python/site-packages/PyPDF2/merger.py", line 203, in append
    self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
  File "/Users/tslankard/Library/Python/3.8/lib/python/site-packages/PyPDF2/merger.py", line 133, in merge
    pdfr = PdfFileReader(fileobj, strict=self.strict)
  File "/Users/tslankard/Library/Python/3.8/lib/python/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/Users/tslankard/Library/Python/3.8/lib/python/site-packages/PyPDF2/pdf.py", line 1696, in read
    raise utils.PdfReadError("EOF marker not found")
PyPDF2.utils.PdfReadError: EOF marker not found

**Comment by TomDSlankard** [comment]
any thoughts?
